title: Zach Alberico
email: hello@zalberico.com
description: Thoughts on software and work in the Bay Area
author: Zach Alberico
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: zachalberico
github_username:  zalberico

# Build settings
markdown: kramdown

# Plugin for RSS
plugins:
  - jekyll-feed
